### ISSUE TITLE
Unable to test it with intent slots resolutions

### ISSUE THREAD

**Issue by mohdasha** [BrianMacIntosh/alexa-skill-test-framework#35]
resolutions.forEach(resolution => {
                            ^

TypeError: resolutions.forEach is not a function
    at Object.addEntityResolutionsToRequest (C:\Users\Mohd Ashif Ali\Documents\GitHub\alexa-greet-my-friend\test\node_modules\alexa-skill-test-framework\index.js:357:15)
    at Suite.<anonymous> (C:\Users\Mohd Ashif Ali\Documents\GitHub\alexa-greet-my-friend\test\greeter-test.js:36:23)
    at Object.create (C:\Users\Mohd Ashif Ali\AppData\Roaming\npm\node_modules\mocha\lib\interfaces\common.js:112:19)
    at context.describe.context.context (C:\Users\Mohd Ashif Ali\AppData\Roaming\npm\node_modules\mocha\lib\interfaces\bdd.js:40:27)
    at Suite.<anonymous> (C:\Users\Mohd Ashif Ali\Documents\GitHub\alexa-greet-my-friend\test\greeter-test.js:30:2)
    at Object.create (C:\Users\Mohd Ashif Ali\AppData\Roaming\npm\node_modules\mocha\lib\interfaces\common.js:112:19)
    at context.describe.context.context (C:\Users\Mohd Ashif Ali\AppData\Roaming\npm\node_modules\mocha\lib\interfaces\bdd.js:40:27)
    at Object.<anonymous> (C:\Users\Mohd Ashif Ali\Documents\GitHub\alexa-greet-my-friend\test\greeter-test.js:18:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at C:\Users\Mohd Ashif Ali\AppData\Roaming\npm\node_modules\mocha\lib\mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (C:\Users\Mohd Ashif Ali\AppData\Roaming\npm\node_modules\mocha\lib\mocha.js:247:14)
    at Mocha.run (C:\Users\Mohd Ashif Ali\AppData\Roaming\npm\node_modules\mocha\lib\mocha.js:576:10)
    at Object.<anonymous> (C:\Users\Mohd Ashif Ali\AppData\Roaming\npm\node_modules\mocha\bin\_mocha:637:18)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

**Comment by sgruendel** [comment]
> resolutions.forEach(resolution => {
> ^
> 
> TypeError: resolutions.forEach is not a function

Parameter resolutions must be an array of resolution objects, for example code see examples/skill-sample-nodejs-slots-and-synonyms/slots-and-synonyms-tests.js.
